### ISSUE TITLE
Integration using a call which will being deprecated

### ISSUE THREAD

**Issue by mattwilson1066** [LucasTor/FoxESS-T-series#5]
Hi @LucasTor I hope all is well. 
Still using this and love it. I happened to be going through some logs today and spotted this message about the integration using a call which will be deprecated and wasn't sure if it was something you were aware of?

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:189

Detected that custom integration 'foxess_tseries' calls async_forward_entry_setup for integration, foxess_tseries with title: FoxESS T Series and entry_id: *********** which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/foxess_tseries/__init__.py, line 11: hass.async_create_task(, please report it to the author of the 'foxess_tseries' custom integration

**Comment by mattwilson1066** [comment]
![Screenshot_20241127-220446.png](https://github.com/user-attachments/assets/62ea7db2-db66-4793-a1f2-3da169108437)

I seem to be having issues with the integration and I'm not sure if it's my setup or something with the integration and HA updates. I'm not getting any data and seem to be generating errors. @LucasTor would you be able to help fault find it suggest where to look?

Cheers

**Comment by mattwilson1066** [comment]
```'None Type' object has no attribute 'loop'

16:31:22 (ERROR) FoxESS T Series (custom integration) - messag..

Unknow error

16:31:22 (ERROR) FoxESS T Series (custom integration) messag...

Invalid message checksum.

14:52:22-(ERROR) FoxESS T Series (custom integration) messag..

Message end marker hit with no start marker.

12:35:54 (WARNING) FOXESS T Series (custom integration)```

**Comment by LucasTor** [comment]
Hey Matt, sorry I didn't see it earlier, did anything change in your setup? That's very weird, it almost seems like the comm between the inverter and the device is broken, sometimes it couldn't find the message header, sometimes it failed to calculate the CRC which means the message got distorted along the way

About the deprecated function, I'll make sure to update that when I have some time in the near future

**Comment by mattwilson1066** [comment]
I have managed to get it working again, I think an HA update must have broken it, but possibly a bit random. So ages ago I disabled a couple of the entities in the Series T integration, the PV3 and PV4 entities as I do not have those on my inverter. This had never caused an issue before, but I'm assuming after an HA update, the fact these entities were disabled and the integration couldn't access them it was causing it to break.

I have included a screenshot from the logs, this is when the entities were disabled it was stopping/breaking. 

<img width="1001" alt="Screenshot 2024-11-29 at 10 17 47" src="https://github.com/user-attachments/assets/6880a31a-f34c-4821-9b88-93647a5dcea0">

With all entities enabled it seems to be happy and working again. Whats also interesting was the data was being received, but it was failing to write to the entity which was causing the error. It might be worth adding in the documentation not to disable any entities that are not in use, leave them all enabled.

**Comment by LucasTor** [comment]
Closing as this was resolved in [this](https://github.com/LucasTor/FoxESS-T-series/pull/7) pr
